name: "Shared CI setup"
description: "Common setup for CI pipeline workflow jobs"
runs:
  using: "composite"
  steps:
    - name: Cargo Cache
      uses: actions/cache@v3
      with:
        path: ~/.cargo
        key: cargo-${{ hashFiles('Cargo.toml') }}
        restore-keys: |
          cargo-${{ hashFiles('Cargo.toml') }}
          cargo

    - name: Cargo Target Cache
      uses: actions/cache@v3
      with:
        path: target
        key: cargo-target-${{ hashFiles('Cargo.toml') }}
        restore-keys: |
          cargo-target-${{ hashFiles('Cargo.toml') }}
          cargo-target

    - name: Read wasmtime version
      id: wasmtime_version
      shell: bash
      run: |
        VERSION=$(cargo metadata --format-version=1 --locked | jq '.packages[] | select(.name == "wasmtime") | .version' -r)
        echo "wasmtime_version=$VERSION" >> "$GITHUB_OUTPUT"

    - name: Install wasmtime-cli
      shell: bash
      run: |
        wget -nv 'https://github.com/bytecodealliance/wasmtime/releases/download/v${{ steps.wasmtime_version.outputs.wasmtime_version }}/wasmtime-v${{ steps.wasmtime_version.outputs.wasmtime_version }}-x86_64-linux.tar.xz' -O /tmp/wasmtime.tar.xz
        mkdir /tmp/wasmtime
        tar xvf /tmp/wasmtime.tar.xz --strip-components=1 -C /tmp/wasmtime
        echo "/tmp/wasmtime" >> $GITHUB_PATH
