name: "Shared CI setup"
description: "Common setup for CI pipeline workflow jobs"
inputs:
  os:
    description: "The operating system for downloading binaries"
    required: true
runs:
  using: "composite"
  steps:
    - name: Cargo Cache
      uses: actions/cache@v3
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
          ${{ runner.os }}-cargo

    - name: Cargo Target Cache
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
          ${{ runner.os }}-cargo-target

    - name: Read wasmtime version
      id: wasmtime_version
      shell: bash
      run: |
        VERSION=$(cargo metadata --format-version=1 --locked | jq '.packages[] | select(.name == "wasmtime") | .version' -r)
        echo "wasmtime_version=$VERSION" >> "$GITHUB_OUTPUT"

    - name: Install wasmtime-cli
      shell: bash
      run: |
        wget -nv 'https://github.com/bytecodealliance/wasmtime/releases/download/v${{ steps.wasmtime_version.outputs.wasmtime_version }}/wasmtime-v${{ steps.wasmtime_version.outputs.wasmtime_version }}-x86_64-${{ inputs.os }}.tar.xz' -O /tmp/wasmtime.tar.xz
        mkdir /tmp/wasmtime
        tar xvf /tmp/wasmtime.tar.xz --strip-components=1 -C /tmp/wasmtime
        echo "/tmp/wasmtime" >> $GITHUB_PATH
