version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    groups:
      nonbreaking:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: npm
    directory: "/npm/javy"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 100

  - package-ecosystem: npm
    directory: "/npm/javy-cli"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 100

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
