version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 100
    groups:
      nonbreaking:
        exclude-patterns:
          - "rquickjs*"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "wasmtime*"

  - package-ecosystem: npm
    directory: "/npm/javy"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 100
    groups:
      nonbreaking:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
