package bytecodealliance:javy-test-plugin@1.0.0;

world javy-test-plugin {
    export compile-src: func(src: list<u8>) -> result<list<u8>, string>;
    export initialize-runtime: func();
    export invoke: func(bytecode: list<u8>, function: option<string>);
    import imported-function: func();
}
