[package]
name = "javy-test-invalid-plugin"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "test_invalid_plugin"
crate-type = ["cdylib"]

[dependencies]
