// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod bytecodealliance {
    pub mod javy_plugin {
        #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
        pub mod imported_functions {
            #[used]
            #[doc(hidden)]
            static __FORCE_SECTION_REF: fn() = super::super::super::__link_custom_section_describing_imports;
            #[allow(unused_unsafe, clippy::all)]
            pub fn imported_function() -> () {
                unsafe {
                    #[cfg(target_arch = "wasm32")]
                    #[link(
                        wasm_import_module = "bytecodealliance:javy-plugin/imported-functions"
                    )]
                    unsafe extern "C" {
                        #[link_name = "imported-function"]
                        fn wit_import0();
                    }
                    #[cfg(not(target_arch = "wasm32"))]
                    unsafe extern "C" fn wit_import0() {
                        unreachable!()
                    }
                    unsafe { wit_import0() };
                }
            }
        }
    }
}
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod bytecodealliance {
        pub mod javy_plugin {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod javy_plugin_exports {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_compile_src_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    let result1 = T::compile_src(
                        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
                    );
                    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec3 = (result1).into_boxed_slice();
                    let ptr3 = vec3.as_ptr().cast::<u8>();
                    let len3 = vec3.len();
                    ::core::mem::forget(vec3);
                    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
                    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
                    ptr2
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_compile_src<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 1, 1);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_initialize_runtime_cabi<T: Guest>() {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    T::initialize_runtime();
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_invoke_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                    arg2: i32,
                    arg3: *mut u8,
                    arg4: usize,
                ) {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let len0 = arg1;
                    T::invoke(
                        _rt::Vec::from_raw_parts(arg0.cast(), len0, len0),
                        match arg2 {
                            0 => None,
                            1 => {
                                let e = {
                                    let len1 = arg4;
                                    let bytes1 = _rt::Vec::from_raw_parts(
                                        arg3.cast(),
                                        len1,
                                        len1,
                                    );
                                    _rt::string_lift(bytes1)
                                };
                                Some(e)
                            }
                            _ => _rt::invalid_enum_discriminant(),
                        },
                    );
                }
                pub trait Guest {
                    fn compile_src(src: _rt::Vec<u8>) -> _rt::Vec<u8>;
                    fn initialize_runtime() -> ();
                    fn invoke(
                        bytecode: _rt::Vec<u8>,
                        function: Option<_rt::String>,
                    ) -> ();
                }
                #[doc(hidden)]
                macro_rules! __export_bytecodealliance_javy_plugin_javy_plugin_exports_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "bytecodealliance:javy-plugin/javy-plugin-exports#compile-src")]
                        unsafe extern "C" fn export_compile_src(arg0 : * mut u8, arg1 :
                        usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_compile_src_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name =
                        "cabi_post_bytecodealliance:javy-plugin/javy-plugin-exports#compile-src")]
                        unsafe extern "C" fn _post_return_compile_src(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_compile_src::<$ty >
                        (arg0) } } #[unsafe (export_name =
                        "bytecodealliance:javy-plugin/javy-plugin-exports#initialize-runtime")]
                        unsafe extern "C" fn export_initialize_runtime() { unsafe {
                        $($path_to_types)*:: _export_initialize_runtime_cabi::<$ty > () }
                        } #[unsafe (export_name =
                        "bytecodealliance:javy-plugin/javy-plugin-exports#invoke")]
                        unsafe extern "C" fn export_invoke(arg0 : * mut u8, arg1 : usize,
                        arg2 : i32, arg3 : * mut u8, arg4 : usize,) { unsafe {
                        $($path_to_types)*:: _export_invoke_cabi::<$ty > (arg0, arg1,
                        arg2, arg3, arg4) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_bytecodealliance_javy_plugin_javy_plugin_exports_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 2 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 2
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub use alloc_crate::vec::Vec;
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub unsafe fn invalid_enum_discriminant<T>() -> T {
        if cfg!(debug_assertions) {
            panic!("invalid enum discriminant")
        } else {
            unsafe { core::hint::unreachable_unchecked() }
        }
    }
    pub use alloc_crate::string::String;
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_javy_plugin_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::bytecodealliance::javy_plugin::javy_plugin_exports::__export_bytecodealliance_javy_plugin_javy_plugin_exports_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::bytecodealliance::javy_plugin::javy_plugin_exports);
    };
}
#[doc(inline)]
pub(crate) use __export_javy_plugin_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:bytecodealliance:javy-plugin:javy-plugin:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 415] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\x9d\x02\x01A\x02\x01\
A\x04\x01B\x02\x01@\0\x01\0\x04\0\x11imported-function\x01\0\x03\0/bytecodeallia\
nce:javy-plugin/imported-functions\x05\0\x01B\x08\x01p}\x01@\x01\x03src\0\0\0\x04\
\0\x0bcompile-src\x01\x01\x01@\0\x01\0\x04\0\x12initialize-runtime\x01\x02\x01ks\
\x01@\x02\x08bytecode\0\x08function\x03\x01\0\x04\0\x06invoke\x01\x04\x04\00byte\
codealliance:javy-plugin/javy-plugin-exports\x05\x01\x04\0(bytecodealliance:javy\
-plugin/javy-plugin\x04\0\x0b\x11\x01\0\x0bjavy-plugin\x03\0\0\0G\x09producers\x01\
\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
