name: javy NPM package CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: javy_npm_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Read wasmtime version
        id: wasmtime_version
        shell: bash
        run: |
          VERSION=$(cargo metadata --format-version=1 --locked \
            | jq -r '.workspace_members as $ws | (.packages|map({(.id):.version})|add) as $ver | [ .resolve.nodes[] | select(.id as $id | $ws|index($id)) | .deps[] | select(.name=="wasmtime") | .pkg ] | map($ver[.]) | unique | first')
          echo "wasmtime_version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Install wasmtime-cli
        shell: bash
        run: |
          wget -nv 'https://github.com/bytecodealliance/wasmtime/releases/download/v${{ steps.wasmtime_version.outputs.wasmtime_version }}/wasmtime-v${{ steps.wasmtime_version.outputs.wasmtime_version }}-x86_64-linux.tar.xz' -O /tmp/wasmtime.tar.xz
          mkdir /tmp/wasmtime
          tar xvf /tmp/wasmtime.tar.xz --strip-components=1 -C /tmp/wasmtime
          echo "/tmp/wasmtime" >> $GITHUB_PATH

      - uses: pnpm/action-setup@v6
        with:
          package_json_file: npm/javy/package.json

      - run: pnpm install
        working-directory: npm/javy

      - run: pnpm test
        working-directory: npm/javy
