name: javy NPM package CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: javy_npm_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Read wasmtime version
        id: wasmtime_version
        shell: bash
        run: |
          VERSION=$(cargo metadata --format-version=1 --locked | jq '.packages[] | select(.name == "wasmtime") | .version' -r)
          echo "wasmtime_version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Install wasmtime-cli
        shell: bash
        run: |
          wget -nv 'https://github.com/bytecodealliance/wasmtime/releases/download/v${{ steps.wasmtime_version.outputs.wasmtime_version }}/wasmtime-v${{ steps.wasmtime_version.outputs.wasmtime_version }}-x86_64-linux.tar.xz' -O /tmp/wasmtime.tar.xz
          mkdir /tmp/wasmtime
          tar xvf /tmp/wasmtime.tar.xz --strip-components=1 -C /tmp/wasmtime
          echo "/tmp/wasmtime" >> $GITHUB_PATH

      - run: npm install
        working-directory: npm/javy

      - run: npm test
        working-directory: npm/javy
