name: NPM package publishing

on:
  push:
    branches:
      - main

jobs:
  publish_npm:
    name: Publish javy NPM package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        with:
          package_json_file: npm/javy/package.json

      - uses: actions/setup-node@v6
        with:
          registry-url: "https://registry.npmjs.org"

      - name: Install package dependencies
        run: pnpm install
        working-directory: npm/javy

      - name: Build NPM package
        run: pnpm run build
        working-directory: npm/javy

      - name: Publish NPM package if new version
        run: |
          if [[ $(cat package.json | jq -r .version) == $(pnpm view javy version) ]]; then
            echo "Skipping publish because the version is already published"
          else
            pnpm publish --no-git-checks
          fi
        working-directory: npm/javy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
